# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=mariadb-user
      - MARIADB_ROOT_PASSWORD=mariadb-root-password
      - MARIADB_PASSWORD=mariadb-password
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'
    networks:
      - network_ds_final_project
  
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin:5.2.0-apache
    ports:
      - '8090:80'
    environment:
      - PMA_ARBITRARY=1
    networks:
      - network_ds_final_project
  
  moodle:
    depends_on:
      - mariadb
    image: docker.io/bitnami/moodle:4.2
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=mariadb-user
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=mariadb-password
      - MOODLE_USERNAME=jhoan.dominguez
      - MOODLE_PASSWORD=jhoan-password
      - MOODLE_EMAIL=jcdominguezj@udistrital.edu.co
      - MOODLE_SITE_NAME=Data Science Programming Lab
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    networks:
      - network_ds_final_project

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

networks:
  network_ds_final_project:
    driver: bridge
  